package com.aavtutov.spring.boot.spring_boot_taxi.dto.mapper;

import org.springframework.stereotype.Component;

import com.aavtutov.spring.boot.spring_boot_taxi.dto.ClientCreateDTO;
import com.aavtutov.spring.boot.spring_boot_taxi.dto.ClientResponseDTO;
import com.aavtutov.spring.boot.spring_boot_taxi.entity.ClientEntity;

/**
 * Spring Component responsible for mapping data between {@link ClientEntity}
 * objects (used internally in the persistence layer) and various Client DTOs
 * (used for API communication).
 */
@Component
public class ClientMapper {

	/**
	 * Converts a {@link ClientEntity} (internal representation) to a
	 * {@link ClientResponseDTO} (API output).
	 *
	 * <p>
	 * Note: Sensitive fields like phone number are typically excluded from the
	 * response DTO.
	 * </p>
	 *
	 * @param client The source client entity.
	 * @return The resulting response DTO containing public client details.
	 */
	public ClientResponseDTO toResponseDto(ClientEntity client) {

		ClientResponseDTO dto = new ClientResponseDTO();
		dto.setId(client.getId());
		dto.setTelegramId(client.getTelegramId());
		dto.setFullName(client.getFullName());

		return dto;
	}

	/**
	 * Converts a {@link ClientResponseDTO} back into a {@link ClientEntity}.
	 *
	 * <p>
	 * This method is typically used when reconstituting an entity from API data,
	 * such as for administrative or internal state updates.
	 * </p>
	 *
	 * @param dto The source response DTO.
	 * @return The resulting client entity.
	 */
	public ClientEntity fromResponseDto(ClientResponseDTO dto) {

		ClientEntity entity = new ClientEntity();
		entity.setId(dto.getId());
		entity.setTelegramId(dto.getTelegramId());
		entity.setFullName(dto.getFullName());

		// Rationale: We intentionally do not map fields that are not present in the DTO
		// (e.g., phoneNumber) as this operation is designed only for basic entity
		// reconstitution.

		return entity;
	}

	/**
	 * Converts a {@link ClientCreateDTO} (API input for creation) to a
	 * {@link ClientEntity}.
	 *
	 * <p>
	 * This mapper is responsible for transferring user-provided registration data
	 * into a new entity instance.
	 * </p>
	 *
	 * @param dto The source creation DTO.
	 * @return The resulting client entity ready for persistence.
	 */
	public ClientEntity fromCreateDto(ClientCreateDTO dto) {

		ClientEntity entity = new ClientEntity();
		// Rationale: ID is deliberately excluded as it will be generated by the
		// persistence mechanism (DB).
		entity.setTelegramId(dto.getTelegramId());
		entity.setPhoneNumber(dto.getPhoneNumber());
		entity.setFullName(dto.getFullName());

		return entity;
	}
}
