package com.aavtutov.spring.boot.spring_boot_taxi.dto.mapper;

import org.springframework.stereotype.Component;

import com.aavtutov.spring.boot.spring_boot_taxi.dto.DriverCreateDTO;
import com.aavtutov.spring.boot.spring_boot_taxi.dto.DriverResponseDTO;
import com.aavtutov.spring.boot.spring_boot_taxi.entity.DriverEntity;

/**
 * Spring Component responsible for mapping data between {@link DriverEntity}
 * objects (used internally in the persistence layer) and various Driver DTOs
 * (used for API communication).
 */
@Component
public class DriverMapper {

	/**
	 * Converts a {@link DriverEntity} (internal representation) to a
	 * {@link DriverResponseDTO} (API output).
	 *
	 * <p>
	 * This mapper includes publicly visible information, such as the vehicle
	 * details, but excludes sensitive fields like document URLs and internal
	 * status.
	 * </p>
	 *
	 * @param entity The source driver entity.
	 * @return The resulting response DTO containing the driver's public profile.
	 */
	public DriverResponseDTO toResponseDto(DriverEntity entity) {

		DriverResponseDTO dto = new DriverResponseDTO();
		dto.setId(entity.getId());
		dto.setTelegramId(entity.getTelegramId());
		dto.setFullName(entity.getFullName());
		dto.setCarModel(entity.getCarModel());
		dto.setCarColor(entity.getCarColor());
		dto.setLicensePlate(entity.getLicensePlate());

		// Rationale: Sensitive fields (driverLicenseUrl, carRegistrationUrl) and
		// internal state (status)
		// are deliberately excluded from the public response DTO.

		return dto;
	}

	/**
	 * Converts a {@link DriverResponseDTO} back into a {@link DriverEntity}.
	 *
	 * <p>
	 * This is typically used for administrative or internal state management where
	 * an entity needs to be reconstituted from the response data structure.
	 * </p>
	 *
	 * @param dto The source response DTO.
	 * @return The resulting driver entity.
	 */
	public DriverEntity fromResponseDto(DriverResponseDTO dto) {

		DriverEntity entity = new DriverEntity();
		entity.setId(dto.getId());
		entity.setTelegramId(dto.getTelegramId());
		entity.setFullName(dto.getFullName());
		entity.setCarModel(dto.getCarModel());
		entity.setCarColor(dto.getCarColor());
		entity.setLicensePlate(dto.getLicensePlate());

		// Rationale: Note that fields required for the entity (like status, document
		// URLs)
		// are not present in the DTO and will be null/default unless handled separately
		// by the service layer during a merge/update operation.

		return entity;
	}

	/**
	 * Converts a {@link DriverCreateDTO} (API input for creation) to a
	 * {@link DriverEntity}.
	 *
	 * <p>
	 * This mapper transfers vehicle and document URLs provided during the
	 * registration process. Essential information (like Telegram ID, Full Name)
	 * must be set by the service layer afterwards.
	 * </p>
	 *
	 * @param dto The source creation DTO containing vehicle and document details.
	 * @return The resulting driver entity containing registration data, ready for
	 *         population of user details.
	 */
	public DriverEntity fromCreateDto(DriverCreateDTO dto) {

		DriverEntity entity = new DriverEntity();
		// Rationale: ID is deliberately excluded as it will be generated by the
		// persistence mechanism (DB).

		// Map vehicle and document details from the DTO
		entity.setCarModel(dto.getCarModel());
		entity.setCarColor(dto.getCarColor());
		entity.setLicensePlate(dto.getLicensePlate());
		entity.setDriverLicenseUrl(dto.getDriverLicenseUrl());
		entity.setCarRegistrationUrl(dto.getCarRegistrationUrl());

		// Rationale: User-specific fields (like Telegram ID, Full Name, and initial
		// Status) are not part of the Create DTO and must be populated by the service
		// layer (e.g., DriverService) after authenticating the user.

		return entity;
	}
}
